language: python
dist: xenial
sudo: true
python:
  - 2.7
  - 3.4
  - 3.5
  - 3.6
  - 3.7
install:
  - pip install .[tests]
script: py.test --verbose --pep8 --flakes --cov falguard --cov-fail-under 100
