language: python
dist: xenial
sudo: true
python:
  - 2.7
  - 3.4
  - 3.5
  - 3.6
  - 3.7
  - 3.8
install:
  - pip install -U .[tests]
script: py.test --verbose --flake8 --pylint --cov falguard --cov-fail-under 100
after_success: bash <(curl -s https://codecov.io/bash)
